// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcGfABIWh0frmuxQs9EVzudHTefi6dQ5w',
    appId: '1:500342287412:web:e19aba6a842b8e81f7ae61',
    messagingSenderId: '500342287412',
    projectId: 'equation-84008',
    authDomain: 'equation-84008.firebaseapp.com',
    storageBucket: 'equation-84008.appspot.com',
    measurementId: 'G-NDW36TQYFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaF5BuwW-tOkeGtButJxdogv4tNOM2b9E',
    appId: '1:500342287412:android:a3dd258c2a6dab93f7ae61',
    messagingSenderId: '500342287412',
    projectId: 'equation-84008',
    storageBucket: 'equation-84008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Eg-LF9MJpxLMyAOohBpsq_Aiyr7z_vs',
    appId: '1:500342287412:ios:be3ba5a8c29542c3f7ae61',
    messagingSenderId: '500342287412',
    projectId: 'equation-84008',
    storageBucket: 'equation-84008.appspot.com',
    iosBundleId: 'com.example.equation',
  );
}
